application:
  accountInfo:
    username: ######
    password: ######
    token: ######
server:
  port: 3001
  #redis


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_music?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-init-sql: set names utf8mb4
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   #使用InnoDB引擎
    show-sql: true

  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒
    timeout: 5000
