application:
  accountInfo:
    username: ######
    password: ######
    token: 5ed61a383a11652211bf35298ca8c14cdabddd47b948ec9fd68641f1d7ff1fec33a649814e309366
server:
  port: 3001
  #redis


spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/febs_base?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://popps.top:3306/db_music?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mdzz@123
    hikari:
      connection-init-sql: set names utf8mb4
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   #使用InnoDB引擎
    show-sql: true

  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒
    timeout: 5000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    #不缓存,页面编写完成后ctrl+F9，就可以看到页面修改的内容
    cache: false
    # 指定模板编码
    encoding: UTF-8
