application:
  accountInfo:
    username: 13049257683
    password: music123.

server:
  port: 3001
  #redis
spring:
  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒
    timeout: 5000
